services:

  ps5-mqtt:
    container_name: ps5-mqtt                            # choose whatever name you like
    hostname: ps5-mqtt
    image: ghcr.io/funkeyflo/ps5-mqtt/amd64:latest      # you can also use a specific version
    entrypoint: /app/run-standalone.sh                      # the file that will be executed at startup
    restart: unless-stopped           
    volumes:                                            # we will use this volume to save credentials
      - /volume1/docker/ps5-mqtt/config:/config
    network_mode: host  
    environment:
      - CONFIG_PATH=/config/options.json
      - DEBUG=@ha:ps5:*    
