services:
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    hostname: dockerproxy    
    environment:
      - CONTAINERS=1
      - IMAGES=1
      - NETWORKS=1
      - VOLUMES=1
      - POST=1          # Required for prune operations
      - TIMEOUT_CLIENT=30m
      - TIMEOUT_SERVER=30m
      - TIMEOUT_CONNECT=5s
    ports:
      - "2375:2375"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
