services:
  duplicati:
      image: lscr.io/linuxserver/duplicati:latest
      container_name: duplicati
      environment:
        - PUID=${RPI_PUID}
        - PGID=${RPI_PGID}        
        - TZ=Asia/Jerusalem
      volumes:
        - /home/dmatik/docker/duplicati/config:/config
        - /home/dmatik/backups:/backups
        - /home/dmatik/docker:/source
      ports:
        - 8200:8200
      restart: unless-stopped
