services:

    watchtower:
        restart: always
        hostname: watchtower
        container_name: watchtower
        image: containrrr/watchtower:latest
        network_mode: "bridge"
        environment:
            TZ: "Asia/Jerusalem"
            WATCHTOWER_CLEANUP: "true"
            WATCHTOWER_SCHEDULE: "0 0 6 * * *"
            WATCHTOWER_NOTIFICATIONS: "shoutrrr"
            WATCHTOWER_NOTIFICATION_REPORT: "true"
            WATCHTOWER_NOTIFICATION_URL: >
                telegram://${MY_DOCKER_BOT_TOKEN}@telegram?channels=${TELEGRAM_CHAT_ID}
                gotify://${GOTIFY_HOST}/${GOTIFY_TOKEN}
            WATCHTOWER_NOTIFICATION_TEMPLATE: |
                {{- if .Report -}}
                  {{- with .Report -}}
                    {{- if ( or .Updated .Failed ) -}}
                {{len .Scanned}} Scanned, {{len .Updated}} Updated, {{len .Failed}} Failed
                      {{- range .Updated}}
                - {{.Name}} ({{.ImageName}}): {{.CurrentImageID.ShortID}} updated to {{.LatestImageID.ShortID}}
                      {{- end -}}
                      {{- range .Skipped}}
                - {{.Name}} ({{.ImageName}}): {{.State}}: {{.Error}}
                      {{- end -}}
                      {{- range .Failed}}
                - {{.Name}} ({{.ImageName}}): {{.State}}: {{.Error}}
                      {{- end -}}
                    {{- end -}}
                  {{- end -}}
                {{- else -}}
                  {{range .Entries -}}{{.Message}}{{"\n"}}{{- end -}}
                {{- end -}}               
            WATCHTOWER_WARN_ON_HEAD_FAILURE: "never"
            WATCHTOWER_NOTIFICATION_TITLE_TAG: "ZEG"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
