services:
  dozzle:
    restart: always
    container_name: dozzle
    hostname: dozzle
    image: amir20/dozzle:latest
    network_mode: bridge
    ports:
      - 9999:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
