services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=${ZEG_PUID}
      - PGID=${ZEG_PGID}
      - TZ=Asia/Jerusalem
    volumes:
      - /volume1/docker/syncthing/config:/config
      - /volume1/syncthing:/syncthing-data
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
