services:
  macos:
    image: dockurr/macos
    container_name: macos
    environment:
      VERSION: "12"
      RAM_SIZE: "512MB"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5900:5900/tcp
      - 5900:5900/udp
    volumes:
      - /volume1/docker/macos/storage:/storage
    restart: always
    stop_grace_period: 2m
