services:

    vaultwarden:
        hostname: vaultwarden
        container_name: vaultwarden
        image: vaultwarden/server:latest
        network_mode: "bridge"
        restart: "always"
        privileged: true
        ports:
            - 5151:80
        environment:
            TZ: "Asia/Jerusalem"
            ADMIN_TOKEN: ${VAULTWARDEN_ADMIN_TOKEN}
            SIGNUPS_ALLOWED: "false"
            DOMAIN: ${VAULTWARDEN_DOMAIN}
        volumes:
          - /volume1/docker/bitwarden/data:/data
