services:

    bitwarden:
        hostname: bitwarden
        container_name: bitwarden
        image: ghcr.io/bitwarden/lite:latest
        network_mode: "bridge"
        restart: "always"
        ports:
            - 9891:8080
        environment:
            TZ: "Asia/Jerusalem"
            BW_DB_PROVIDER: "sqlite"
            BW_DOMAIN: ${BW_LITE_DOMAIN}
            BW_INSTALLATION_ID: ${BW_LITE_INSTALLATION_ID}
            BW_INSTALLATION_KEY: ${BW_LITE_INSTALLATION_KEY}
        volumes:
          - /volume1/docker/bitwardenlite/data:/etc/bitwarden
