services:

  pulse:
    image: rcourtman/pulse:latest
    container_name: pulse
    hostname: pulse
    restart: unless-stopped
    ports:
      - "7655:7655"
    volumes:
      - /volume1/docker/pulse/data:/data
    environment:
        TZ: "Asia/Jerusalem"      
