services:

    zigbee2mqtt:
        container_name: zigbee2mqtt
        image: koenkk/zigbee2mqtt
        restart: unless-stopped
        volumes:
          - /home/dmatik/docker/zigbee2mqtt/data:/app/data
          - /run/udev:/run/udev:ro
        ports:
          # Frontend port
          - 8080:8080
        environment:
          - TZ=Asia/Jerusalem
        devices:
          # Make sure this matched your adapter location
          - /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2119426-if00:/dev/ttyACM0
