services:

    zigbee2mqtt:
        container_name: zigbee2mqtt
        image: koenkk/zigbee2mqtt
        restart: unless-stopped
        volumes:
          - /home/dmatik/docker/zigbee2mqtt/data:/app/data
          - /run/udev:/run/udev:ro
        ports:
          # Frontend port
          - 8080:8080
        environment:
          - TZ=Asia/Jerusalem
        devices:
          # Make sure this matched your adapter location
          - /dev/serial/by-id/usb-Nabu_Casa_Home_Assistant_Connect_ZBT-1_1628a37950eced11aeff0f1d62c613ac-if00-port0:/dev/ttyUSB0
        labels:
          - com.centurylinklabs.watchtower.monitor-only=true          
